// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvA1Yab1R7qTvaxYG_vVS_5vqqfEL_-fs',
    appId: '1:230036257870:web:0ff04eeff315b84fb4171f',
    messagingSenderId: '230036257870',
    projectId: 'intern-project-f75de',
    authDomain: 'intern-project-f75de.firebaseapp.com',
    storageBucket: 'intern-project-f75de.appspot.com',
    measurementId: 'G-R2T9G5MZ7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrfYW9BYz0CBKHwkEdi0-xafr_1tO-Q8o',
    appId: '1:230036257870:android:e4dd876e720bc84fb4171f',
    messagingSenderId: '230036257870',
    projectId: 'intern-project-f75de',
    storageBucket: 'intern-project-f75de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoPEdDzb0jqR_dzmLrW4mLYLl9EMD358Q',
    appId: '1:230036257870:ios:8cd662544a61da2bb4171f',
    messagingSenderId: '230036257870',
    projectId: 'intern-project-f75de',
    storageBucket: 'intern-project-f75de.appspot.com',
    iosClientId: '230036257870-8kdgldnjb2f1v9i8pns4n0f7phc0lff8.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoPEdDzb0jqR_dzmLrW4mLYLl9EMD358Q',
    appId: '1:230036257870:ios:8cd662544a61da2bb4171f',
    messagingSenderId: '230036257870',
    projectId: 'intern-project-f75de',
    storageBucket: 'intern-project-f75de.appspot.com',
    iosClientId: '230036257870-8kdgldnjb2f1v9i8pns4n0f7phc0lff8.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipTesting',
  );
}
