// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKHfAEaUWmpyRnjdPK_ahA7LsHCH27B3E',
    appId: '1:862194057019:web:61fa14bbfefc056a64811e',
    messagingSenderId: '862194057019',
    projectId: 'sample-cc37b',
    authDomain: 'sample-cc37b.firebaseapp.com',
    storageBucket: 'sample-cc37b.appspot.com',
    measurementId: 'G-J7VKC1WXZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFEXvyrsx_u3Z2tlzUs0WK8Ey8SGAhSfk',
    appId: '1:862194057019:android:05048ee581f8ae4c64811e',
    messagingSenderId: '862194057019',
    projectId: 'sample-cc37b',
    storageBucket: 'sample-cc37b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxDBALc2TajIjLUMPjHHYOoCCJBOkEOLI',
    appId: '1:862194057019:ios:a38d16846c8330d164811e',
    messagingSenderId: '862194057019',
    projectId: 'sample-cc37b',
    storageBucket: 'sample-cc37b.appspot.com',
    iosClientId: '862194057019-kphpvppl1jotd99h18hnjbouodvhg0p6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxDBALc2TajIjLUMPjHHYOoCCJBOkEOLI',
    appId: '1:862194057019:ios:a38d16846c8330d164811e',
    messagingSenderId: '862194057019',
    projectId: 'sample-cc37b',
    storageBucket: 'sample-cc37b.appspot.com',
    iosClientId: '862194057019-kphpvppl1jotd99h18hnjbouodvhg0p6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample',
  );
}
